// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9OnYqNPR6BPX8XOUpIjn2VCHe9_Dim8',
    appId: '1:391673501114:web:bed52b5afbc7150105b983',
    messagingSenderId: '391673501114',
    projectId: 'quick-chop-eb2db',
    authDomain: 'quick-chop-eb2db.firebaseapp.com',
    storageBucket: 'quick-chop-eb2db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOd8Mb7Y3afpiqYzW-MH1TNcyndLLT98E',
    appId: '1:391673501114:android:230568c498a8021e05b983',
    messagingSenderId: '391673501114',
    projectId: 'quick-chop-eb2db',
    storageBucket: 'quick-chop-eb2db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIVUq0jeMdvtXd3sPtA1jD6dPfjikdOxw',
    appId: '1:391673501114:ios:b1940e069766f66205b983',
    messagingSenderId: '391673501114',
    projectId: 'quick-chop-eb2db',
    storageBucket: 'quick-chop-eb2db.appspot.com',
    iosBundleId: 'com.example.quickChop',
  );
}
